baseurl = "https://lissetbejar.github.io"
title = "lisset.place"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
canonifyurls = true
languageCode = "en-us"
MetaDataFormat = "toml"
[indexes] 
    category = "categories"
    tag = "tags"
[author] 
    name = "Lisset Bejar"
[permalinks]
    post = "/:year/:slug/"
    page = "/:slug/"
[params]
  description = "The website of Lisset Bejar"
[markup.highlight]
style = "monokailight"
[markup.goldmark.renderer]
unsafe= true
